name: oms-ci-workflow

on: [pull_request]

jobs:
  build:
  
    runs-on: ubuntu-latest

    steps:
    
    - name: Clone main repository
      uses: actions/checkout@v2
      with:
        submodules: recursive
        token: ${{ secrets.MY_PERSONAL_KEY_AS_ORG_KEY }}
        
    - name: Update submodules recursively
      run:
        git submodule update --init --remote --recursive
        
    - name: Install gtest manually
      run: sudo apt-get install libgtest-dev
    
    - name: Debug build
      run: |
        mkdir build-debug
        cd build-debug
        cmake ..
        cmake --build . --target all --config Debug
    
    - name: Release build
      run: |
        mkdir build-release
        cd build-release
        cmake ..
        cmake --build . --target all --config Release
    - name: Debug test
      run: |
        cd build-debug
        cd tests
        ./test_mem
    
    - name: Release test
      run: |
        cd build-release
        cd tests
        ./test_mem
